### ISSUE TITLE
Stream URL no longer displayed

### ISSUE THREAD

**Issue by Dong1337** [Maxam0001/TikTokLiveStreamURLHelper#1]
Hi, since today the stream URL is no longer displayed

![image](https://user-images.githubusercontent.com/67829783/132046947-cf7993c2-cb2c-44a2-97b1-0a969c49cbbd.png)

**Comment by Maxam0001** [comment]
Unfortunately, TikTok fixed the leaking HLS url that I was extracting in the original version of the script. We're still able to get the FLV link, but that's less useful than the HLS url we were getting before.

In any case, I made a quick patch. It works locally, but I'm not sure if the signature I used for the new call is going to expire. Feel free to check it out.

**Comment by Dong1337** [comment]
Hi, thankyou for the quick fix. Do you know of any software that will download these without stopping whenever the stream freezes?

**Comment by Maxam0001** [comment]
I use VLC Player to record these, as YoutubeDL and its variants don't handle packet drops very well. Click File/Open Network Stream, then hit Record when the stream loads. You can set buffering in the options.
