### ISSUE TITLE
fetchRoomInfo

### ISSUE THREAD

**Issue by CLICK-HERE-SEE-MY-HOT-VIDEOS-BBBBB** [Maxam0001/TikTokLiveStreamURLHelper#2]
fetchRoomInfo returns 500, the interface is updated

**Comment by Maxam0001** [comment]
I tried it just a few minutes ago and it worked.

![image](https://user-images.githubusercontent.com/86354594/136993911-49af2d51-8810-49e4-b156-eb61f68597f1.png)

**Comment by Maxam0001** [comment]
Since there is no additional feedback, I am closing this issue.
