### ISSUE TITLE
Button and URL no longer displaying after update

### ISSUE THREAD

**Issue by Dong1337** [Maxam0001/TikTokLiveStreamURLHelper#3]
Hi, TikTok have done a horrible update to the website and the script no longer works.

I've changed the class it looks for to "eth61t00" which seems have fixed the missing button, however when i click it i get "Could not retrieve Stream URL"

Any ideas how to fix this?

Thanks in advance

**Comment by Maxam0001** [comment]
TikTok's changes were rather huge, so I tried to implement the simplest fix for now. This new code works for me, not sure if it works for everyone else.

**Comment by Dong1337** [comment]
Amazing, the m3u8 link is back, thank you!
