### ISSUE TITLE
It still works, but....

### ISSUE THREAD

**Issue by spinningsand** [Maxam0001/TikTokLiveStreamURLHelper#6]
....what all can I do with it? I can stream it in VLC, but what else can I do with it? Is there a way you can play it after the stream ends or get the whole stream while it's still live? I noticed I could still get the stream link after it ended, but it wouldn't play in VLC. Can I change that?

**Comment by mklaber** [comment]
You can use [ffmpeg](https://ffmpeg.org/) to download it to MP4:

```
ffmpeg -stats -loglevel quiet -user_agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/537.86.7" -i "THE_LIVE_STREAM_URL" -c copy "NAME_OF_FILE.mp4"
```

You can then replay the stream.

**Comment by spinningsand** [comment]
I'm having trouble getting it to work. I tried the user agent for both firefox and Chrome and tried it on streams that were still live and on ones that ended, but it doesn't seem to do anything, there are no outputs only sits there for a few seconds. I searched to see if the mp4 was saved and couldn't find it either.

**Comment by spinningsand** [comment]
I did find some other commands that lets you convert the stream url to mp4 but they only work on streams that are still live. Is that what yours does as well or can it work after the stream ends too?

Also, sorry for answering you back so late. I somehow missed the notification before.

**Comment by mklaber** [comment]
Streams must be live for it to work.
