### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by whittinghamj** [Maxam0001/TikTokLiveStreamURLHelper#9]
as of 08/27/24 this is no longer working form what I can tell.

**Comment by Maxam0001** [comment]
I just tried it five minutes ago and it worked. Try logging in first if you don't see the "Get Stream URL" link.

**Comment by whittinghamj** [comment]
Could you please provide a full source code working example of how you got this working?

please and thank you.

**Comment by Maxam0001** [comment]
Code? This is Github. The code is right there. I didn't need to change anything from the current version to use it yesterday.

**Comment by whittinghamj** [comment]
I mean how did you use the .js file - maybe I used it incorrectly

**Comment by Maxam0001** [comment]
As mentioned in the readme, this is a Greasemonkey script. You use it with the Greasemonkey browser add-on.

**Comment by whittinghamj** [comment]
https://capture.dropbox.com/a0AIdfHs3HB26G6r

**Comment by Maxam0001** [comment]
https://imgur.com/VXtwTfZ

Works just fine here.
